#if DEBUG
import Foundation

nonisolated struct TranscriptionProofReport: Codable, Sendable, Equatable {
    var schemaVersion: Int
    var status: String
    var phase: String
    var startedAt: Date
    var updatedAt: Date
    var completedAt: Date?
    var engine: TranscriptionProofEngine
    var feedURL: String
    var podcastTitle: String?
    var episodeTitle: String?
    var episodeID: String?
    var publishedAt: Date?
    var declaredDuration: TimeInterval?
    var sourceAudioURL: String?
    var sourceFilePath: String?
    var sourceFileByteCount: Int64?
    var sourceFileSHA256: String?
    var modelIdentifier: String?
    var modelVersion: String?
    var modelTreeSHA256: String?
    var modelByteCount: Int64?
    var computeProfile: String?
    var audioDuration: TimeInterval?
    var completedDuration: TimeInterval?
    var checkpointCount: Int?
    var segmentCount: Int?
    var wordedSegmentCount: Int?
    var wordCount: Int?
    var textCharacterCount: Int?
    var textPreview: String?
    var transcriptRelativePath: String?
    var transcriptFilePath: String?
    var modelLoading: TimeInterval?
    var audioLoading: TimeInterval?
    var transcription: TimeInterval?
    var fullPipeline: TimeInterval?
    var realTimeFactor: Double?
    var decodingWindowCount: Int?
    var decodingFallbackCount: Int?
    var appleSpeechRequestedLocaleIdentifier: String?
    var appleSpeechResolvedLocaleIdentifier: String?
    var appleSpeechAssetStatus: String?
    var appleSpeechInstalledLocaleIdentifiers: [String]
    var appleSpeechRequiresInstalledAssets: Bool?
    var appleSpeechAllowsAssetInstallation: Bool?
    var speechRecognizerAuthorizationStatus: String?
    var errorMessage: String?
    var checkpoints: [TranscriptionProofCheckpointReport]

    init(feedURL: URL, engine: TranscriptionProofEngine = .whisper, startedAt: Date = .now) {
        schemaVersion = 1
        status = "running"
        phase = "starting"
        self.startedAt = startedAt
        updatedAt = startedAt
        completedAt = nil
        self.engine = engine
        self.feedURL = feedURL.absoluteString
        podcastTitle = nil
        episodeTitle = nil
        episodeID = nil
        publishedAt = nil
        declaredDuration = nil
        sourceAudioURL = nil
        sourceFilePath = nil
        sourceFileByteCount = nil
        sourceFileSHA256 = nil
        modelIdentifier = nil
        modelVersion = nil
        modelTreeSHA256 = nil
        modelByteCount = nil
        computeProfile = nil
        audioDuration = nil
        completedDuration = nil
        checkpointCount = nil
        segmentCount = nil
        wordedSegmentCount = nil
        wordCount = nil
        textCharacterCount = nil
        textPreview = nil
        transcriptRelativePath = nil
        transcriptFilePath = nil
        modelLoading = nil
        audioLoading = nil
        transcription = nil
        fullPipeline = nil
        realTimeFactor = nil
        decodingWindowCount = nil
        decodingFallbackCount = nil
        appleSpeechRequestedLocaleIdentifier = nil
        appleSpeechResolvedLocaleIdentifier = nil
        appleSpeechAssetStatus = nil
        appleSpeechInstalledLocaleIdentifiers = []
        appleSpeechRequiresInstalledAssets = nil
        appleSpeechAllowsAssetInstallation = nil
        speechRecognizerAuthorizationStatus = nil
        errorMessage = nil
        checkpoints = []
    }
}
#endif
