// Generated by scripts/sync-screenshots.mjs. Do not edit by hand.
export const screenshotAssets = {
  "app_store_01_skip_framed": {
    "src": "/screenshots/app_store_01_skip_framed.ddb40939e6.w464.png",
    "avifSrcSet": "/screenshots/app_store_01_skip_framed.91e949a784.w232.avif 232w, /screenshots/app_store_01_skip_framed.316e151ada.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_01_skip_framed.0e68ea36a4.w232.webp 232w, /screenshots/app_store_01_skip_framed.8d02f793aa.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_02_transcript_framed": {
    "src": "/screenshots/app_store_02_transcript_framed.8251549df2.w464.png",
    "avifSrcSet": "/screenshots/app_store_02_transcript_framed.8028a7950e.w232.avif 232w, /screenshots/app_store_02_transcript_framed.ab2f8b9085.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_02_transcript_framed.a247e8d59e.w232.webp 232w, /screenshots/app_store_02_transcript_framed.6e62590df2.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_03_sound_lab_framed": {
    "src": "/screenshots/app_store_03_sound_lab_framed.8a0d48a1e2.w464.png",
    "avifSrcSet": "/screenshots/app_store_03_sound_lab_framed.48d0781a25.w232.avif 232w, /screenshots/app_store_03_sound_lab_framed.92cc580654.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_03_sound_lab_framed.df2ba2b70e.w232.webp 232w, /screenshots/app_store_03_sound_lab_framed.9c0319f8c0.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_04_search_framed": {
    "src": "/screenshots/app_store_04_search_framed.27b368d2c2.w464.png",
    "avifSrcSet": "/screenshots/app_store_04_search_framed.2eddee123f.w232.avif 232w, /screenshots/app_store_04_search_framed.164856b451.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_04_search_framed.81aaea7bda.w232.webp 232w, /screenshots/app_store_04_search_framed.f7e1913a65.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_05_chapters_framed": {
    "src": "/screenshots/app_store_05_chapters_framed.78530bfd18.w464.png",
    "avifSrcSet": "/screenshots/app_store_05_chapters_framed.f29484673c.w232.avif 232w, /screenshots/app_store_05_chapters_framed.d03e013f47.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_05_chapters_framed.dd5fe99ce7.w232.webp 232w, /screenshots/app_store_05_chapters_framed.74edd3332c.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_06_pipeline_framed": {
    "src": "/screenshots/app_store_06_pipeline_framed.20c3af29f8.w464.png",
    "avifSrcSet": "/screenshots/app_store_06_pipeline_framed.205c6ca8c4.w232.avif 232w, /screenshots/app_store_06_pipeline_framed.ecfbd90993.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_06_pipeline_framed.f5d1f093cc.w232.webp 232w, /screenshots/app_store_06_pipeline_framed.f3ebfaf899.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_07_notification_framed": {
    "src": "/screenshots/app_store_07_notification_framed.4c2fbc8aa0.w464.png",
    "avifSrcSet": "/screenshots/app_store_07_notification_framed.accfc05c48.w232.avif 232w, /screenshots/app_store_07_notification_framed.784a38499c.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_07_notification_framed.74eeeb280e.w232.webp 232w, /screenshots/app_store_07_notification_framed.4a63ba1882.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_08_library_framed": {
    "src": "/screenshots/app_store_08_library_framed.f0d631907c.w464.png",
    "avifSrcSet": "/screenshots/app_store_08_library_framed.785b2d2b33.w232.avif 232w, /screenshots/app_store_08_library_framed.3f88029dce.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_08_library_framed.8c58f758f2.w232.webp 232w, /screenshots/app_store_08_library_framed.10ea6c164f.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_09_welcome_framed": {
    "src": "/screenshots/app_store_09_welcome_framed.2d33fa2b8b.w464.png",
    "avifSrcSet": "/screenshots/app_store_09_welcome_framed.91c7e5b926.w232.avif 232w, /screenshots/app_store_09_welcome_framed.b218ed25d2.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_09_welcome_framed.c9de45a87d.w232.webp 232w, /screenshots/app_store_09_welcome_framed.34c4871bfb.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_10_up_next_framed": {
    "src": "/screenshots/app_store_10_up_next_framed.fde44d8723.w464.png",
    "avifSrcSet": "/screenshots/app_store_10_up_next_framed.07494c922f.w232.avif 232w, /screenshots/app_store_10_up_next_framed.dca1d24b8c.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_10_up_next_framed.5900d12d46.w232.webp 232w, /screenshots/app_store_10_up_next_framed.d0f456975b.w464.webp 464w",
    "width": 464,
    "height": 1008
  }
} as const;
