// Generated by scripts/sync-screenshots.mjs. Do not edit by hand.
export const screenshotAssets = {
  "app_store_01_now_playing_framed": {
    "src": "/screenshots/app_store_01_now_playing_framed.b67b3e3ca3.w464.png",
    "avifSrcSet": "/screenshots/app_store_01_now_playing_framed.427358d0a7.w232.avif 232w, /screenshots/app_store_01_now_playing_framed.56796d808f.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_01_now_playing_framed.a6f5bfebef.w232.webp 232w, /screenshots/app_store_01_now_playing_framed.20bd0861aa.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_02_transcript_framed": {
    "src": "/screenshots/app_store_02_transcript_framed.e4625ab0cf.w464.png",
    "avifSrcSet": "/screenshots/app_store_02_transcript_framed.adc5eafbe5.w232.avif 232w, /screenshots/app_store_02_transcript_framed.2b86ca49d1.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_02_transcript_framed.4ac8aadbed.w232.webp 232w, /screenshots/app_store_02_transcript_framed.ad5f1058f6.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_03_notification_framed": {
    "src": "/screenshots/app_store_03_notification_framed.73ccbc933d.w464.png",
    "avifSrcSet": "/screenshots/app_store_03_notification_framed.905579ef89.w232.avif 232w, /screenshots/app_store_03_notification_framed.48e0bd3c7b.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_03_notification_framed.ffd045f08f.w232.webp 232w, /screenshots/app_store_03_notification_framed.5398602e90.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_04_library_framed": {
    "src": "/screenshots/app_store_04_library_framed.9d5037ca55.w464.png",
    "avifSrcSet": "/screenshots/app_store_04_library_framed.2454ceb682.w232.avif 232w, /screenshots/app_store_04_library_framed.4e22a923d1.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_04_library_framed.1eb761523f.w232.webp 232w, /screenshots/app_store_04_library_framed.1af75423f5.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_05_podcast_detail_framed": {
    "src": "/screenshots/app_store_05_podcast_detail_framed.6613e44e4f.w464.png",
    "avifSrcSet": "/screenshots/app_store_05_podcast_detail_framed.163f9a0da9.w232.avif 232w, /screenshots/app_store_05_podcast_detail_framed.1da98ceae2.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_05_podcast_detail_framed.68ccdb78e2.w232.webp 232w, /screenshots/app_store_05_podcast_detail_framed.9a4eb0a6d5.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_06_sound_lab_framed": {
    "src": "/screenshots/app_store_06_sound_lab_framed.7909ea64e0.w464.png",
    "avifSrcSet": "/screenshots/app_store_06_sound_lab_framed.4d10fd38b0.w232.avif 232w, /screenshots/app_store_06_sound_lab_framed.f28a425c32.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_06_sound_lab_framed.51b417e34a.w232.webp 232w, /screenshots/app_store_06_sound_lab_framed.a8ab359d1d.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_07_inbox_framed": {
    "src": "/screenshots/app_store_07_inbox_framed.daf43c5331.w464.png",
    "avifSrcSet": "/screenshots/app_store_07_inbox_framed.41e1c09e18.w232.avif 232w, /screenshots/app_store_07_inbox_framed.94fa003c4e.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_07_inbox_framed.82f71420dc.w232.webp 232w, /screenshots/app_store_07_inbox_framed.9fd7d1da23.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_08_episode_detail_framed": {
    "src": "/screenshots/app_store_08_episode_detail_framed.e6274897cb.w464.png",
    "avifSrcSet": "/screenshots/app_store_08_episode_detail_framed.7fe3ff62db.w232.avif 232w, /screenshots/app_store_08_episode_detail_framed.17692a830e.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_08_episode_detail_framed.562c77725a.w232.webp 232w, /screenshots/app_store_08_episode_detail_framed.bea63bbe12.w464.webp 464w",
    "width": 464,
    "height": 1008
  }
} as const;
