// Generated by scripts/sync-screenshots.mjs. Do not edit by hand.
export const screenshotAssets = {
  "app_store_01_now_playing_framed": {
    "src": "/screenshots/app_store_01_now_playing_framed.897d9dd404.w464.png",
    "avifSrcSet": "/screenshots/app_store_01_now_playing_framed.df6489afc5.w232.avif 232w, /screenshots/app_store_01_now_playing_framed.838a4849ed.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_01_now_playing_framed.5d8787c276.w232.webp 232w, /screenshots/app_store_01_now_playing_framed.1e1aff1937.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_02_transcript_framed": {
    "src": "/screenshots/app_store_02_transcript_framed.5b028aeb3b.w464.png",
    "avifSrcSet": "/screenshots/app_store_02_transcript_framed.f7f866095b.w232.avif 232w, /screenshots/app_store_02_transcript_framed.19ef6c5a93.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_02_transcript_framed.8a0caf2eb0.w232.webp 232w, /screenshots/app_store_02_transcript_framed.893f12afa5.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_03_notification_framed": {
    "src": "/screenshots/app_store_03_notification_framed.58e277aaf1.w464.png",
    "avifSrcSet": "/screenshots/app_store_03_notification_framed.e3e8310a6c.w232.avif 232w, /screenshots/app_store_03_notification_framed.037a00045f.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_03_notification_framed.91045c0db7.w232.webp 232w, /screenshots/app_store_03_notification_framed.9d64c0b83f.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_04_library_framed": {
    "src": "/screenshots/app_store_04_library_framed.773d9e34e5.w464.png",
    "avifSrcSet": "/screenshots/app_store_04_library_framed.31c2c56c92.w232.avif 232w, /screenshots/app_store_04_library_framed.d93f12353c.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_04_library_framed.793fd8bcd5.w232.webp 232w, /screenshots/app_store_04_library_framed.0558d46f07.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_05_podcast_detail_framed": {
    "src": "/screenshots/app_store_05_podcast_detail_framed.feb8de7e67.w464.png",
    "avifSrcSet": "/screenshots/app_store_05_podcast_detail_framed.b2477d397e.w232.avif 232w, /screenshots/app_store_05_podcast_detail_framed.6cc82bc4b3.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_05_podcast_detail_framed.c2fc9a7bff.w232.webp 232w, /screenshots/app_store_05_podcast_detail_framed.5b7e1a46c5.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_06_sound_lab_framed": {
    "src": "/screenshots/app_store_06_sound_lab_framed.d5d1ce97d3.w464.png",
    "avifSrcSet": "/screenshots/app_store_06_sound_lab_framed.c482be569b.w232.avif 232w, /screenshots/app_store_06_sound_lab_framed.2b2b187631.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_06_sound_lab_framed.4833bd9241.w232.webp 232w, /screenshots/app_store_06_sound_lab_framed.a4a455f9b6.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_07_inbox_framed": {
    "src": "/screenshots/app_store_07_inbox_framed.eeb3a5da44.w464.png",
    "avifSrcSet": "/screenshots/app_store_07_inbox_framed.5fada6795d.w232.avif 232w, /screenshots/app_store_07_inbox_framed.5705199b7b.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_07_inbox_framed.7c4fa1ba02.w232.webp 232w, /screenshots/app_store_07_inbox_framed.43d48f3604.w464.webp 464w",
    "width": 464,
    "height": 1008
  },
  "app_store_08_episode_detail_framed": {
    "src": "/screenshots/app_store_08_episode_detail_framed.bcd3739ee1.w464.png",
    "avifSrcSet": "/screenshots/app_store_08_episode_detail_framed.5ac53d7367.w232.avif 232w, /screenshots/app_store_08_episode_detail_framed.9b5a74bab2.w464.avif 464w",
    "webpSrcSet": "/screenshots/app_store_08_episode_detail_framed.6673bfc6fa.w232.webp 232w, /screenshots/app_store_08_episode_detail_framed.95bf34e22c.w464.webp 464w",
    "width": 464,
    "height": 1008
  }
} as const;
