[package]
name = "opencast-app-attest-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
base64 = "0.22"
byteorder = "1.5"
constant_time_eq = "0.4"
futures-util = "0.3"
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4"
minicbor = "0.25"
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
p384 = { version = "0.13.1", default-features = false, features = ["ecdsa"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
worker = { version = "0.8", features = ["d1"] }
x509-parser = "0.18"

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1
